container:
  type: ColumnPanel
  properties: {col_widths: '{}'}
components:
- type: DataGrid
  properties:
    role: tonal-data-grid
    columns:
    - {id: ZTAFTV, title: Name, data_key: name, $$hashKey: 'object:1031'}
    - {id: XDMCKE, title: Description, data_key: description, $$hashKey: 'object:1033'}
    - {id: KWBLPW, title: SKU, data_key: sku, $$hashKey: 'object:1032'}
    - {id: ZOJBFS, title: Qty, data_key: '', $$hashKey: 'object:1072'}
    - {id: PIZUMC, title: '', data_key: column_1, $$hashKey: 'object:233212'}
    auto_header: true
    tooltip: ''
    border: ''
    foreground: ''
    rows_per_page: 20
    visible: true
    wrap_on: never
    show_page_controls: true
    spacing_above: small
    spacing_below: small
    background: ''
  name: data_grid_1
  layout_properties: {grid_position: 'LWQTZS,AQISRF'}
  components:
  - type: Button
    properties: {role: null, align: center, tooltip: '', border: '', enabled: true,
      foreground: '', visible: true, text: 'import

        ', font_size: null, font: '', spacing_above: small, icon_align: left, spacing_below: small,
      italic: false, background: '', bold: false, underline: false, icon: ''}
    name: button_1
    layout_properties: {}
    event_bindings: {click: button_1_click}
  - type: RepeatingPanel
    properties: {spacing_above: none, spacing_below: none, item_template: Homepage.Inventory.RowTemplate1}
    name: repeating_panel_1
    layout_properties: {}
    data_bindings:
    - {property: items, code: 'self.item[''products'']'}
is_package: true
