container:
  type: ColumnPanel
  properties: {col_widths: '{}'}
components:
- type: GridPanel
  properties: {}
  name: grid_panel_1
  layout_properties: {grid_position: 'HPTSBW,AMAQZM'}
  components:
  - type: Label
    properties: {role: null, align: left, tooltip: '', border: '', foreground: '',
      visible: true, text: 'Last Sync:', font_size: null, font: '', spacing_above: medium,
      icon_align: left, spacing_below: none, italic: false, background: '', bold: false,
      underline: false, icon: ''}
    name: label_sync
    layout_properties: {row: CPBFWL, width_xs: 2, col_xs: 0, width: 99.9875}
  - type: Label
    properties: {role: null, align: left, tooltip: '', border: '', foreground: '',
      visible: true, text: '', font_size: null, font: '', spacing_above: medium, icon_align: left,
      spacing_below: none, italic: false, background: '', bold: false, underline: false,
      icon: ''}
    name: label_latest_sync
    layout_properties: {row: CPBFWL, width_xs: 3, col_xs: 0, width: 165}
    data_bindings:
    - {property: text, code: 'self.item[0][''last_sync'']'}
  - type: Button
    properties: {role: filled-button, align: right, tooltip: '', border: '', enabled: true,
      foreground: '', visible: true, text: Sync Wix Data, font_size: null, font: '',
      spacing_above: medium, icon_align: left, spacing_below: none, italic: false,
      background: '', bold: false, underline: false, icon: 'fa:refresh'}
    name: button_sync
    layout_properties: {row: CPBFWL, width_xs: 3, col_xs: 8, width: 165}
    event_bindings: {click: button_sync_click}
is_package: true
